import { generateUUID } from '../utils/uuid';
import { CATEGORY_KEYS } from '../constants/categories';
import { randomInt, shuffleArray } from './tablesGenerator';
import wordBank from '../data/wordBank.json';

/**
 * Generate a vocabulary question from the word bank.
 * Format: "What does 'WORD' mean?"
 * Hint: manualExamples → autoGeneratedExample fallback → null
 *
 * @param {Set<number>} usedWordIds - Set of already-used wordIds to avoid repeats
 * @returns {Object} Question object
 */
export const generateVocabQuestion = (usedWordIds) => {
  // Pick a random unused word
  const availableWords = wordBank.filter((w) => !usedWordIds.has(w.wordId));
  if (availableWords.length === 0) {
    throw new Error('No more available words in the word bank.');
  }

  const word = availableWords[randomInt(0, availableWords.length - 1)];
  usedWordIds.add(word.wordId);

  // Correct answer
  const correctMeaning = word.Meaning;

  // Distractors: 3 random meanings from other words
  const distractorPool = wordBank
    .filter((w) => w.wordId !== word.wordId && w.Meaning !== correctMeaning)
    .map((w) => w.Meaning);

  const shuffledPool = shuffleArray(distractorPool);
  const distractorMeanings = shuffledPool.slice(0, 3);

  // Build options
  const allMeanings = shuffleArray([correctMeaning, ...distractorMeanings]);
  const options = allMeanings.map((meaning) => ({
    answerId: generateUUID(),
    answerValue: meaning,
  }));

  const correctOption = options.find((o) => o.answerValue === correctMeaning);

  // Resolve hint
  const hint = resolveHint(word);

  return {
    questionId: generateUUID(),
    questionDescription: `What does '${word.Word}' mean?`,
    categoryType: CATEGORY_KEYS.VOCABULARY,
    possibleAnswers: options,
    correctAnswer: { answerId: correctOption.answerId, answerValue: correctOption.answerValue },
    hint,
  };
};

/**
 * Generate N vocabulary questions
 * @param {number} count
 * @returns {Array}
 */
export const generateVocabQuestions = (count) => {
  const usedWordIds = new Set();
  const questions = [];

  for (let i = 0; i < count; i++) {
    questions.push(generateVocabQuestion(usedWordIds));
  }

  return questions;
};

/**
 * Resolve hint for a vocabulary word.
 * Priority: manualExamples → autoGeneratedExample → null
 * @param {Object} word - Word bank entry
 * @returns {string|null}
 */
function resolveHint(word) {
  if (word.manualExamples && word.manualExamples !== '—' && word.manualExamples.trim() !== '') {
    return word.manualExamples;
  }
  if (word.autoGeneratedExample && word.autoGeneratedExample !== '—' && word.autoGeneratedExample.trim() !== '') {
    return word.autoGeneratedExample;
  }
  return null;
}
